items/urls.py
from django.urls import path

from items.views import index, good_detail, goods_by_category, goods_by_manufacture, goods_by_tag

app_name = 'items'

urlpatterns = [
    path('', index, name='index'),
    path('good_detail/<int:good_id>', good_detail, name='good-detail'),
    path('goods_by_category/<int:category_id>', goods_by_category, name='goods-by-category'),
    path('goods_by_manufacture/<int:manufacture_id>', goods_by_manufacture, name='goods-by-manufacture'),
    path('goods_by_tag/<int:tag_id>', goods_by_tag, name='goods-by-tag'),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('items.urls', namespace='items')),
    path('admin/', admin.site.urls),
]

items/models.py
from django.db import models

from items.constants import MAX_LENGTH_CHAR_FIELD, MAX_LENGTH_PHONE_NUMBER

class Category(models.Model):
    name = models.CharField(verbose_name='Категория', max_length=MAX_LENGTH_CHAR_FIELD)
    description = models.CharField(verbose_name='Описание', max_length=MAX_LENGTH_CHAR_FIELD)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Manufacture(models.Model):
    name = models.CharField(verbose_name='Название', max_length=MAX_LENGTH_CHAR_FIELD)
    address = models.TextField(verbose_name='Адрес')
    phone = models.CharField(verbose_name='Телефон', max_length=MAX_LENGTH_PHONE_NUMBER)
    latest_update = models.DateTimeField(verbose_name='Последнее обновление')

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name


class Tag(models.Model):
    color = models.CharField(verbose_name='Цвет', max_length=MAX_LENGTH_CHAR_FIELD)
    name = models.CharField(verbose_name='Название', max_length=MAX_LENGTH_CHAR_FIELD)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class Good(models.Model):
    name = models.CharField(verbose_name='Название', max_length=MAX_LENGTH_CHAR_FIELD)
    description = models.CharField(verbose_name='Описание', max_length=MAX_LENGTH_CHAR_FIELD)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name='goods',
        blank=True,
        null=True,
        verbose_name='Категория',
    )
    manufacture = models.ForeignKey(
        Manufacture,
        on_delete=models.SET_NULL,
        related_name='goods',
        blank=True,
        null=True,
        verbose_name='Производитель',
    )
    tags = models.ManyToManyField(Tag, related_name='goods')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser


class Profile(AbstractUser):
    pass

items/views.py
from django.shortcuts import render, get_object_or_404

from items.models import Tag, Category, Manufacture, Good


def index(request):
    goods = Good.objects.all()

    context = {
        'goods': goods,
    }

    return render(request, 'items/index.html', context)


def good_detail(request, good_id):
    good = get_object_or_404(Good.objects.select_related('category', 'manufacture'), id=good_id)

    context = {
        'good': good,
    }

    return render(request, 'items/good_detail.html', context)


def goods_by_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    goods = category.goods.all()

    context = {
        'type': 'категории',
        'name': category.name,
        'goods': goods,
    }

    return render(request, 'items/goods_by.html', context)


def goods_by_manufacture(request, manufacture_id):
    manufacture = get_object_or_404(Manufacture, id=manufacture_id)
    goods = manufacture.goods.all()

    context = {
        'type': 'производителю',
        'name': manufacture.name,
        'goods': goods,
    }

    return render(request, 'items/goods_by.html', context)


def goods_by_tag(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id)
    goods = tag.goods.all()

    context = {
        'type': 'тегу',
        'name': tag.name,
        'goods': goods,
    }

    return render(request, 'items/goods_by.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/items/good_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ good.name }}</title>
</head>
<body>
    <h1>{{ good.name }}</h1>
    {% for tag in good.tags.all %}
        <a href="{% url 'items:goods-by-tag' tag.id %}"><font color="{{ tag.color }}"> #{{ tag.name }}</font></a>
    {% endfor %}
    <h3>{{ good.description }}</h3>
    <div>Категория: <a href="{% url 'items:goods-by-category' good.category.id %}">{{ good.category.name }}</a></div>
    <div>Производитель: <a href="{% url 'items:goods-by-manufacture' good.manufacture.id %}">{{ good.manufacture.name }}</a></div>
</body>
</html>

templates/items/goods_by.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Товары по {{ type }} "{{ name }}"</title>
</head>
<body>
    <h1>Товары по {{ type }} "{{ name }}"</h1>
    <ul>
        {% for good in goods %}
            <li><b>{{ good.name }}</b> - {{ good.description }} (<a href="{% url 'items:good-detail' good.id %}">подробнее</a>)</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/items/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная страница нового маркета</title>
</head>
<body>
    <h1>Главная страница нового маркета</h1>
    <h3>Топ-3 товаров</h3>
    <ul>
        {% for good in goods %}
            <li><b>{{ good.name }}</b> - {{ good.description }} (<a href="{% url 'items:good-detail' good.id %}">подробнее</a>)</li>
        {% endfor %}
    </ul>
</body>
</html>